version: "3.7"
services:
  db57:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "3306:${MYSQL_PORT}"
    volumes:
      - mysql-backend:/var/lib/mysql
  app:
    user: $DOCKER_USER
    image: node:18-alpine3.14
    working_dir: /prova
    env_file:
      - .env
    environment: 
      - MYSQL_HOST=db57
    command: sh -c "npm i && npm run dev"
    ports:
      - "${PORT}:${PORT}"
      - "8080:8080"
    volumes:
      - "./:/prova"

    depends_on: 
      - db57
volumes:
  mysql-backend:
    driver: local